{ pkgs, inputs, ... }:

{
  home.packages = with pkgs; [
    discord
    alsa-utils
    btop
    fastfetch
    crosspipe
    cool-retro-term
    kdePackages.okular
    kdePackages.kolourpaint
    obsidian
    pamixer
    pavucontrol
    pulseaudio
    chromium
    inputs.zen-browser.packages.${pkgs.stdenv.hostPlatform.system}.default
    libreoffice-fresh
    telegram-desktop
    bruno
    transmission_4-gtk
    networkmanagerapplet
    blueman
    thunar
    thunar-volman
    thunar-archive-plugin
    tumbler
    grim
    slurp
    grimblast
    swappy
    wl-clipboard
    awww
    vial
    qmk
    qt6.qtwayland
    qt6.qtimageformats
    kdePackages.kio
    kdePackages.kio-extras
    eza
    bat
    lavat
    trash-cli
    uv
    inputs.antigravity-nix.packages.${pkgs.stdenv.hostPlatform.system}.google-antigravity
    inputs.antigravity-nix.packages.${pkgs.stdenv.hostPlatform.system}.google-antigravity-cli
  ];
}
